# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# disable autocorrect
unsetopt correct
unsetopt correct_all

# oh-my-zsh git plugin
source ~/git/oh-my-zsh/plugins/git/git.plugin.zsh

export PATH="/usr/local/sbin:/usr/local/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/danielque/bin"
PATH=$PATH:~/local/bin

# Load zsh-autosuggestions.
source ~/.zsh/zsh-autosuggestions/zsh-autosuggestions.zsh

ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE='fg=3'

set -o vi
bindkey '^e' end-of-line
bindkey '^a' beginning-of-line
bindkey '^R' history-incremental-pattern-search-backward
export EDITOR=vim
export VISUAL=vim

## fix backspace in zsh
bindkey '^?' backward-delete-char
bindkey '^H' backward-delete-char

source /usr/local/bin/virtualenvwrapper.sh

# it would be nice to have this, but autosuggestions conflicts with it :( https://github.com/junegunn/fzf
[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh
bindkey "\e[3~" delete-char

# Aliases
unalias rm
alias ctg='ctags -R .'  # must be exuberant ctags

function cx { cd "$@" && ls }

function mkcd { mkdir "$@" && cd "$@" }

# tensorflow
export CUDA_HOME=/usr/local/cuda
export DYLD_LIBRARY_PATH="$DYLD_LIBRARY_PATH:$CUDA_HOME/lib"
export PATH="$CUDA_HOME/bin:$PATH"

# nvm (commented because it's super slow)
#export NVM_DIR="$HOME/.nvm"
#source /usr/local/opt/nvm/nvm.sh
